### ISSUE TITLE
npm start 后接口报错

### ISSUE THREAD

**Issue by ddzyan** [justjavac/v8.js.cn#57]
```shell
git clone https://github.com/justjavac/v8.js.cn.git

cd v8.js.cn

npm install

yarn start
```
打开 http://localhost:9001/ 报错如下
![image](https://user-images.githubusercontent.com/9130123/118426589-10848200-b6fe-11eb-84b6-a4ae330955a9.png)

**Comment by justjavac** [comment]
有没有 nodejs 的报错信息？

**Comment by justjavac** [comment]
需要先运行 `npm run watch`

**Comment by ddzyan** [comment]
感谢，这对我是有用的
